const JOB_TITLES = [
  'Mayor',
  'Town Crier',
  'Town Clerk',
  'Town Historian',
  'Baker',
  'Librarian',
  'Postal Carrier',
  'Doctor',
  'Dentist',
  'Pharmacist',
  'Veterinarian',
  'Barber',
  'Hairdresser',
  'Florist',
  'Butcher',
  'Grocer',
  'Tailor',
  'Locksmith',
  'Plumber',
  'Electrician',
  'Carpenter',
  'Mechanic',
  'Landscaper',
  'Beekeeper',
  'Farmer',
  'Fisherman',
  'Innkeeper',
  'Hotel Manager',
  'Diner Owner',
  'Bartender',
  'Barista',
  'Chef',
  'Pastry Chef',
  'Food Vendor',
  'Market Vendor',
  'Antique Dealer',
  'Bookshop Owner',
  'Record Store Owner',
  'Photographer',
  'Mural Artist',
  'Sign Painter',
  'Tattoo Artist',
  'Street Musician',
  'DJ',
  'Radio Host',
  'Local Reporter',
  'Newspaper Editor',
  'Museum Curator',
  'Park Ranger',
  'Tour Guide',
  'Bus Driver',
  'Taxi Driver',
  'Crossing Guard',
  'Lifeguard',
  'Fire Chief',
  'Sheriff',
  'Deputy',
  'Night Watchman',
  'Security Guard',
  'Judge',
  'Lawyer',
  'Notary',
  'Accountant',
  'Banker',
  'Realtor',
  'Architect',
  'City Planner',
  'Council Member',
  'School Teacher',
  'Principal',
  'Coach',
  'Referee',
  'Scout Leader',
  'Choir Director',
  'Church Organist',
  'Pastor',
  'Yoga Instructor',
  'Personal Trainer',
  'Nutritionist',
  'Therapist',
  'Social Worker',
  'Handyman',
  'Janitor',
  'Weather Forecaster',
  'Theater Director',
  'Stagehand',
  'Ticket Seller',
  'Local Legend',
  'Neighborhood Watch',
  'PTA President',
  'Block Captain',
  'Old-Timer',
  'Newcomer',
] as const

export const ROLES = JOB_TITLES.map((title) => `Tomo's ${title}` as const)

export type Role = (typeof ROLES)[number]

export function randomRole(): Role {
  return ROLES[Math.floor(Math.random() * ROLES.length)]
}

export function isValidRole(value: unknown): value is Role {
  return typeof value === 'string' && (ROLES as readonly string[]).includes(value)
}
