-- URGENT fix: the live "Get your ID" flow is broken right now.
--
-- app/api/citizens/route.ts always computes and inserts an explicit
-- citizen_number itself (via lib/nextCitizenNumber.ts, so intentional gaps
-- from the Figma batches are never auto-filled). That only works if the
-- column is GENERATED BY DEFAULT. My last migration script restored it to
-- GENERATED ALWAYS at the end, which rejects any explicit value -- breaking
-- every new signup with error 428C9.
--
-- GENERATED BY DEFAULT is the correct persistent state for this column going
-- forward. Do not run anything that sets it back to GENERATED ALWAYS.

ALTER TABLE citizens ALTER COLUMN citizen_number SET GENERATED BY DEFAULT;
