-- Fix: the pre-existing "NALIN SEMWAL" placeholder citizen was bumped to
-- #300 as part of the tomoland-6.19-new-cards migration, which accidentally
-- collided with "hamza ali" (a new card whose mockup explicitly specified
-- TOMO-0300). Moves the bumped placeholder out of the way to #307, and
-- advances the identity sequence past it so future signups don't collide.

BEGIN;

ALTER TABLE citizens ALTER COLUMN citizen_number SET GENERATED BY DEFAULT;

UPDATE citizens SET citizen_number = 307 WHERE id = '1f5cd7fc-1dac-4f8f-bae2-12e178eeb4ab'; -- NALIN SEMWAL (placeholder, bumped)

SELECT setval(pg_get_serial_sequence('public.citizens','citizen_number'), 308, false);

ALTER TABLE citizens ALTER COLUMN citizen_number SET GENERATED ALWAYS;

COMMIT;
