-- Restore kiosk-assigned resident numbers for party guests already in citizens.
-- Run once in Supabase -> SQL Editor after migrate-party-to-main assigned fresh
-- directory numbers instead of copying party_citizens.citizen_number.
--
-- Matches party rows to directory rows by photo_url (kiosk uploads use photos/party-*).
-- Gaps in the directory sequence (e.g. missing #71) are expected and fine.

BEGIN;

ALTER TABLE public.citizens ALTER COLUMN citizen_number SET GENERATED BY DEFAULT;

UPDATE public.citizens c
SET citizen_number = p.citizen_number
FROM public.party_citizens p
WHERE c.photo_url IS NOT NULL
  AND p.photo_url IS NOT NULL
  AND c.photo_url = p.photo_url
  AND c.citizen_number IS DISTINCT FROM p.citizen_number;

-- Guests who skipped the photo step — match on name + role when both lack a photo.
UPDATE public.citizens c
SET citizen_number = p.citizen_number
FROM public.party_citizens p
WHERE c.photo_url IS NULL
  AND p.photo_url IS NULL
  AND c.name = p.name
  AND c.relation_to_tomo = p.relation_to_tomo
  AND c.citizen_number IS DISTINCT FROM p.citizen_number
  AND NOT EXISTS (
    SELECT 1
    FROM public.party_citizens p2
    WHERE p2.photo_url IS NULL
      AND p2.name = p.name
      AND p2.relation_to_tomo = p.relation_to_tomo
      AND p2.id <> p.id
  );

SELECT setval(
  pg_get_serial_sequence('public.citizens', 'citizen_number'),
  (SELECT COALESCE(MAX(citizen_number), 1) FROM public.citizens),
  true
);

ALTER TABLE public.citizens ALTER COLUMN citizen_number SET GENERATED ALWAYS;

COMMIT;

-- Verify — kiosk_id should equal directory_id for every matched row.
SELECT
  p.citizen_number AS kiosk_number,
  p.tomoland_id AS kiosk_id,
  p.name,
  c.citizen_number AS directory_number,
  c.tomoland_id AS directory_id,
  CASE
    WHEN c.id IS NULL THEN 'missing from citizens'
    WHEN c.citizen_number = p.citizen_number THEN 'ok'
    ELSE 'still mismatched'
  END AS status
FROM public.party_citizens p
LEFT JOIN public.citizens c
  ON (
    (c.photo_url IS NOT NULL AND p.photo_url IS NOT NULL AND c.photo_url = p.photo_url)
    OR (
      c.photo_url IS NULL
      AND p.photo_url IS NULL
      AND c.name = p.name
      AND c.relation_to_tomo = p.relation_to_tomo
    )
  )
ORDER BY p.citizen_number;
