-- Migration: tomoland-6.19-new-cards batch 2 (Figma node 29:10857)
-- Run once in Supabase -> SQL Editor.
--
-- All 6 of these people already exist in the directory as generic
-- 'Tomo's Friend' seed placeholders. This REPLACES each one in place
-- (same id, so ownership/history is preserved) with their real card from
-- this batch: number, relation, name casing, and photo.
--
-- No renumbering needed -- none of the 6 target numbers (50, 51, 121,
-- 123, 125, 126) are currently occupied by anyone else.

BEGIN;

ALTER TABLE citizens ALTER COLUMN citizen_number SET GENERATED BY DEFAULT;

UPDATE citizens SET citizen_number = 121, name = 'MAJA WILBRINK', relation_to_tomo = 'TOMO''S LORE AUTHOR', photo_url = 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-6cb473be-39e3-448e-9f67-8ba49d917093.png' WHERE id = 'a6759808-bcc5-49ab-84bb-818ae73bd743'; -- TOMO-0121 MAJA WILBRINK
UPDATE citizens SET citizen_number = 125, name = 'CHRISSY SUN', relation_to_tomo = 'TOMO''S TRIPLET', photo_url = 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-e7d76645-d46b-4cf4-9387-9e3322ec9e07.png' WHERE id = 'd64f26b3-d810-46ce-99b1-be899a1f490d'; -- TOMO-0125 CHRISSY SUN
UPDATE citizens SET citizen_number = 126, name = 'JENNY SUN', relation_to_tomo = 'TOMO''S TRIPLET', photo_url = 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-2b8cb96c-ebf5-4c7f-b559-b0987b2f554d.png' WHERE id = 'ea75fe69-1724-4f4b-8ee0-c8d13116c7ef'; -- TOMO-0126 JENNY SUN
UPDATE citizens SET citizen_number = 123, name = 'AMY ZHOU', relation_to_tomo = 'TOMO''S PRETZEL BAKER', photo_url = 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-49b8824c-7473-43f7-98af-d133a90358e0.png' WHERE id = '97f19f57-63cf-410c-89f2-e0779ef4e66f'; -- TOMO-0123 AMY ZHOU
UPDATE citizens SET citizen_number = 51, name = 'RYAN KIM', relation_to_tomo = 'TOMO''S GUARDIAN ANGEL', photo_url = 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-f6e91bcf-67f2-49e7-8ec1-36d56bfbf057.png' WHERE id = '432b268c-5903-4b6f-aaba-81fd197ddfc9'; -- TOMO-0051 RYAN KIM
UPDATE citizens SET citizen_number = 50, name = 'Christina Melas-KyriazI', relation_to_tomo = 'TOMO''S GUARDIAN ANGEL', photo_url = 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-acc6d62a-ce13-4e0f-a24a-98ffce48ccb4.png' WHERE id = '965ea3f4-7ba7-4258-bee4-0c4ac6f331e2'; -- TOMO-0050 Christina Melas-KyriazI

ALTER TABLE citizens ALTER COLUMN citizen_number SET GENERATED ALWAYS;

COMMIT;
