-- Migration: tomoland-6.19-new-cards batch (Figma node 7:10016)
-- Run once in Supabase -> SQL Editor.
--
-- 1) Bumps 28 pre-existing citizens whose numbers collide with this new
--    batch's mockup numbers to the bottom of the directory (highest numbers).
-- 2) Inserts all 40 new citizens at their exact mockup-specified numbers.
--    Three mockup numbers are intentionally shared by two new citizens each
--    (Resham Khanna/Collin Ochs both TOMO-0151, shweta katyal/Morgan Malloch
--    both TOMO-0163, celina you/Will Eleazer both TOMO-0138) -- duplicate
--    numbers here are expected, per instruction.

BEGIN;

ALTER TABLE citizens ALTER COLUMN citizen_number SET GENERATED BY DEFAULT;

-- Bump pre-existing citizens out of the way (move to bottom)
UPDATE citizens SET citizen_number = 279 WHERE id = '5e3058a8-7a4d-4ea0-9501-2f371ea7ff45'; -- was #135 ANNIE MA
UPDATE citizens SET citizen_number = 280 WHERE id = '037bfd28-15c3-4716-9a92-6edf4deb2eb3'; -- was #136 ARMAN KUMARASWAMY
UPDATE citizens SET citizen_number = 281 WHERE id = '5fcb9059-1a49-492d-ad3b-b46757f7784a'; -- was #137 BASSIL SHAMA
UPDATE citizens SET citizen_number = 282 WHERE id = '82d7c04f-e435-48bd-bc27-2dfa0b6781f8'; -- was #138 BILL
UPDATE citizens SET citizen_number = 283 WHERE id = 'a33d6d88-d89f-40d5-9780-1d0f64eb42fd'; -- was #139 CHARLES GAO
UPDATE citizens SET citizen_number = 284 WHERE id = '369a8dfa-a78b-4104-be83-1b3cfbc20837'; -- was #145 FOY
UPDATE citizens SET citizen_number = 285 WHERE id = '76fa431f-cde1-49a9-a643-f388cd31bc6d'; -- was #147 HYDEN POLIKOFF
UPDATE citizens SET citizen_number = 286 WHERE id = '9b9b3567-d43c-42d8-8619-613decf5bd85'; -- was #148 JACKIE CHEN
UPDATE citizens SET citizen_number = 287 WHERE id = '43e56a4d-d2ca-47dd-bd81-dbb6375c37f0'; -- was #149 JAE PARK
UPDATE citizens SET citizen_number = 288 WHERE id = 'ea75fe69-1724-4f4b-8ee0-c8d13116c7ef'; -- was #150 JENNY SUN
UPDATE citizens SET citizen_number = 289 WHERE id = '5c08fef6-0122-4247-bd04-84fc948620e4'; -- was #151 JIA CHEN
UPDATE citizens SET citizen_number = 290 WHERE id = '588ef8a1-4c94-4993-8b77-62c224a6f0be'; -- was #153 KAITLYN LUO
UPDATE citizens SET citizen_number = 291 WHERE id = '642f151d-daf3-44e4-bc6e-f57bb3e525e1'; -- was #154 KER LEE YAP
UPDATE citizens SET citizen_number = 292 WHERE id = 'a6759808-bcc5-49ab-84bb-818ae73bd743'; -- was #155 MAJA WILBRINK
UPDATE citizens SET citizen_number = 293 WHERE id = 'b672ef48-4e79-4d4d-a4d1-207f1e18ef30'; -- was #156 MATHURAH RAVIGULAN
UPDATE citizens SET citizen_number = 294 WHERE id = '4bd64b6c-1c1d-48c5-8e23-6c084adede60'; -- was #157 MATTHEW GUILLOD
UPDATE citizens SET citizen_number = 295 WHERE id = '48d1c483-af80-4fd1-9294-a41a9e9e8818'; -- was #158 MEGAN MOU
UPDATE citizens SET citizen_number = 296 WHERE id = '983bebd0-e3a7-4e8a-a181-467dfff55a30'; -- was #159 MEI MEI
UPDATE citizens SET citizen_number = 297 WHERE id = 'ffebc008-af64-4f9d-b649-3cb142ebd9f3'; -- was #160 MICHAEL ZHU
UPDATE citizens SET citizen_number = 298 WHERE id = 'dc22c592-a4ad-4c16-99cc-2cb14e5eea82'; -- was #161 MICHELLE SCHWARTZMAN
UPDATE citizens SET citizen_number = 299 WHERE id = '0cbf8c44-e0ea-4380-a8fe-57213ec98f50'; -- was #162 MING
UPDATE citizens SET citizen_number = 300 WHERE id = '1f5cd7fc-1dac-4f8f-bae2-12e178eeb4ab'; -- was #163 NALIN SEMWAL
UPDATE citizens SET citizen_number = 301 WHERE id = '09c7d02e-3588-41b3-b488-e97bbdcd6377'; -- was #164 NICK O''BRIEN
UPDATE citizens SET citizen_number = 302 WHERE id = '2bfa3a02-ed3a-4e0b-9189-574ea023c47f'; -- was #165 NICOLE SUMMER HSING
UPDATE citizens SET citizen_number = 303 WHERE id = 'f2e16407-32dc-4bcb-a68c-c33ac92a8875'; -- was #166 RAYMOND MA QUAN
UPDATE citizens SET citizen_number = 304 WHERE id = '235dcb04-82f2-47fb-bd6e-7890f587e154'; -- was #167 ROHIL AGARWAL
UPDATE citizens SET citizen_number = 305 WHERE id = '432b268c-5903-4b6f-aaba-81fd197ddfc9'; -- was #168 RYAN KIM
UPDATE citizens SET citizen_number = 306 WHERE id = 'fc4802ab-93d1-4a44-845c-0c975ee6e5c5'; -- was #169 SHAAHANA NAUFAL

-- Insert new citizens at their exact mockup numbers (duplicates intentional, see header)
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (145, 'Kaustubh Prabhakar', 'TOMO''S PRESENT DELIVERY MAN', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-e6dbdb1c-4ada-4a65-a68e-76c199210493.png'); -- TOMO-0145
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (147, 'NICOLE SEAH', 'TOMO''S SECRET KEEPER', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-ec07c536-4aee-461a-8ffc-7117583b48d8.png'); -- TOMO-0147
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (148, 'KASEY ZHANG', 'TOMO''S HILL CLIMBER', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-51619882-1f2f-4511-bfd1-1beaff13bfe3.png'); -- TOMO-0148
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (149, 'Shreyas Parab', 'TOMO''S DENTIST', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-a5fedcb9-78ed-4a67-a9a1-055088526aba.png'); -- TOMO-0149
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (150, 'Pierce Daly', 'TOMO''S COWBOY', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-bda1ed10-f484-43c0-b9e3-d8733c33925c.png'); -- TOMO-0150
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (151, 'Resham Khanna', 'TOMO''S ART TUTOR', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-32f2aedb-5c17-45ee-af42-d82fdef51a10.png'); -- TOMO-0151
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (153, 'Sofie Johnson', 'Tomo''s Power Walker', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-d965d3fd-c856-4bad-ab68-a029233ccf27.png'); -- TOMO-0153
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (154, 'John Ferrara', 'Tomo''s Globemaker', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-b46082e5-c5e4-4fed-b5a7-3ed303fd3e86.png'); -- TOMO-0154
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (155, 'JESSICA SUN', 'Tomo''s Ex-RetooL', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-eefdea78-f80c-4d49-99a4-7bf7b98d398e.png'); -- TOMO-0155
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (156, 'Karine Hsu', 'Tomo''s Baked BaddY', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-b5626e4b-9772-4aa5-876b-4427fd10cc5c.png'); -- TOMO-0156
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (157, 'GRACE HUA', 'Tomo''s SECURITY GUARD', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-db1952ae-74c0-4995-aeab-d3fd568401aa.png'); -- TOMO-0157
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (158, 'Kaitlyn Luo', 'Tomo''s KAT', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-0e789040-2933-4849-af1f-71e4dbb8193d.png'); -- TOMO-0158
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (159, 'CHRISTINE ZHANG', 'Tomo''s Eshay BahhH', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-bb252d2d-c9db-4130-89e7-6821b3029a0c.png'); -- TOMO-0159
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (160, 'Nicole Loza', 'Tomo''s Bombshell', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-b099d478-83db-45a6-81ca-f2a88e7636de.png'); -- TOMO-0160
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (161, 'SIMON WIJCKMANS', 'Tomo''s BOUNCER', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-6abb5260-c4b8-4d03-a0dc-e024f57a342b.png'); -- TOMO-0161
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (162, 'Sophie Fuji', 'Tomo''s philosopher', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-7b795fea-41ba-41e5-b6d4-98c0f805f702.png'); -- TOMO-0162
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (163, 'shweta katyal', 'Tomo''s shitposter', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-f9e2f91d-2da0-44a2-bd97-ef0f55c3de66.png'); -- TOMO-0163
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (164, 'Ann Bordetsky', 'Tomo''s magician', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-34c21c7c-d572-4b56-968e-7f1d95df9e94.png'); -- TOMO-0164
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (165, 'Umesh Khanna', 'Tomo''s forward deployed angel', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-d98e049d-eafc-4edb-b609-663bedcd47ac.png'); -- TOMO-0165
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (166, 'Chloe Barreau', 'Tomo''s playmate', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-c1d59378-fff9-410a-86b2-3421b8b7ef44.png'); -- TOMO-0166
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (167, 'Shriya Bhat', 'Tomo''s band director', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-61b958de-391e-4b73-89d4-ac2104e1a1e4.png'); -- TOMO-0167
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (168, 'sammi', 'Tomo''s interior decorator', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-e838401a-1e5d-4efb-8255-ff6a72f4db62.png'); -- TOMO-0168
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (169, 'haris', 'Tomo''s pet sitter', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-44e54ad4-307b-42f5-83ed-58f6082c2517.png'); -- TOMO-0169
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (135, 'ADEL WU', 'TOMO''S PORTRAIT ARTIST', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-f6146ad1-cb37-4c95-9309-c69c9aa5a072.png'); -- TOMO-0135
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (136, 'melisa SEAH', 'TOMO''S BEDTIME STORY READER', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-7b5fac02-e764-48c2-a71d-8ac3d2904d3d.png'); -- TOMO-0136
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (137, 'EMILY HAN', 'TOMO''S ART TEACHER', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-8ca87860-4839-4889-b830-d0d45645265a.png'); -- TOMO-0137
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (138, 'celina you', 'TOMO''S MATCHA FARMER', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-0bfa4a61-a973-4cea-8ddd-70dec4b9bbf2.png'); -- TOMO-0138
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (139, 'AMANDA HUANG', 'TOMO''S NANNY', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-fee32704-6794-4944-b26d-da4b9b1d1b48.png'); -- TOMO-0139
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (122, 'Mathurah Ravigulan', 'TOMO''S FRIEND', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-cfe01680-8cd9-4464-af72-baf9ed053c62.png'); -- TOMO-0122
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (124, 'NALIN SEMWAL', 'TOMO''S FRIEND', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-ecf6fdb3-bf7b-4706-97e4-a963e5cdf198.png'); -- TOMO-0124
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (109, 'ERIKA LEE', 'TOMO''S BABYSITTER', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-6e2c46dc-b373-46e2-b929-db54c6f10eef.png'); -- TOMO-0109
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (110, 'Ipshita Agarwal', 'TOMO''S PROFESSOR', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-8c3ee01e-902f-49ea-aeb7-ac344b5b2f00.png'); -- TOMO-0110
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (107, 'TRUDY', 'TOMO''S FURRY FRIEND', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-43d1fa53-04e5-4cad-848a-74f23ca1248a.png'); -- TOMO-0107
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (108, 'BROOKE LEBLANC', 'TOMO''S GODMOTHER', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-b6e58564-404c-4e81-a4cd-92cb470f589c.png'); -- TOMO-0108
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (111, 'Lukas Levert', 'TOMO''S SURF INSTRUCTOR', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-ce966569-701c-456a-a436-86e3f08435a4.png'); -- TOMO-0111
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (112, 'JOHN HUTTON', 'TOMO''S X PLUG', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-c588b2ec-f1b3-4e89-a274-bbf5d34298d5.png'); -- TOMO-0112
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (300, 'hamza ali', 'TOMO''S PILOT', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-c74dd8db-5700-4883-8a7f-1bacf89f3fe3.png'); -- TOMO-0300
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (151, 'COLLIN OCHS', 'Tomo''s Pacer', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-a35a19bd-f467-4a20-94cc-96e5021e2174.png'); -- TOMO-0151
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (163, 'Morgan Malloch', 'Tomo''s magician', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-2473869b-2e95-4910-a052-eef819aa4a6a.png'); -- TOMO-0163
INSERT INTO citizens (citizen_number, name, relation_to_tomo, place_of_issue, photo_url) VALUES (138, 'Will Eleazer', 'TOMO''S BABYSITTER', 'San Francisco, CA', 'https://ucryvowkqdbtczggabdx.supabase.co/storage/v1/object/public/citizen-photos/photos/figma-88a1d692-8045-49e0-8f42-ada8ebcd2d68.png'); -- TOMO-0138

SELECT setval(pg_get_serial_sequence('public.citizens','citizen_number'), 307, false);

ALTER TABLE citizens ALTER COLUMN citizen_number SET GENERATED ALWAYS;

COMMIT;
