-- Post-party migration — copy party_citizens into citizens with kiosk numbers intact.
-- Run once in Supabase -> SQL Editor after the event (before or instead of the .mjs script).
--
-- Skips rows already present (matched by photo_url, or name+role when photoless).

BEGIN;

ALTER TABLE public.citizens ALTER COLUMN citizen_number SET GENERATED BY DEFAULT;

INSERT INTO public.citizens (
  citizen_number,
  name,
  relation_to_tomo,
  place_of_issue,
  photo_url
)
SELECT
  p.citizen_number,
  p.name,
  p.relation_to_tomo,
  p.place_of_issue,
  p.photo_url
FROM public.party_citizens p
WHERE NOT EXISTS (
  SELECT 1
  FROM public.citizens c
  WHERE (
    c.photo_url IS NOT NULL
    AND p.photo_url IS NOT NULL
    AND c.photo_url = p.photo_url
  )
  OR (
    c.photo_url IS NULL
    AND p.photo_url IS NULL
    AND c.name = p.name
    AND c.relation_to_tomo = p.relation_to_tomo
  )
)
ORDER BY p.created_at ASC;

SELECT setval(
  pg_get_serial_sequence('public.citizens', 'citizen_number'),
  (SELECT COALESCE(MAX(citizen_number), 1) FROM public.citizens),
  true
);

ALTER TABLE public.citizens ALTER COLUMN citizen_number SET GENERATED ALWAYS;

COMMIT;
