-- Renumbers Albert Tian and the next 49 citizens after him (by citizen_number)
-- to resident numbers 130–179. Gaps left at their old numbers (14–62, etc.) are fine.
--
-- Run once in Supabase -> SQL Editor.

BEGIN;

ALTER TABLE public.citizens ALTER COLUMN citizen_number SET GENERATED BY DEFAULT;

WITH albert AS (
  SELECT citizen_number AS start_num
  FROM public.citizens
  WHERE name = 'Albert Tian'
  LIMIT 1
),
cohort AS (
  SELECT
    sub.id,
    ROW_NUMBER() OVER (ORDER BY sub.citizen_number) - 1 AS idx
  FROM (
    SELECT c.id, c.citizen_number
    FROM public.citizens c
    CROSS JOIN albert a
    WHERE c.citizen_number >= a.start_num
    ORDER BY c.citizen_number
    LIMIT 50
  ) sub
)
UPDATE public.citizens c
SET citizen_number = c.citizen_number + 2000
FROM cohort co
WHERE c.id = co.id;

WITH albert AS (
  SELECT citizen_number AS start_num
  FROM public.citizens
  WHERE name = 'Albert Tian'
  LIMIT 1
),
cohort AS (
  SELECT
    sub.id,
    ROW_NUMBER() OVER (ORDER BY sub.citizen_number) - 1 AS idx
  FROM (
    SELECT c.id, c.citizen_number
    FROM public.citizens c
    CROSS JOIN albert a
    WHERE c.citizen_number >= a.start_num
    ORDER BY c.citizen_number
    LIMIT 50
  ) sub
)
UPDATE public.citizens c
SET citizen_number = 130 + co.idx
FROM cohort co
WHERE c.id = co.id;

SELECT setval(
  pg_get_serial_sequence('public.citizens', 'citizen_number'),
  (SELECT COALESCE(MAX(citizen_number), 1) FROM public.citizens),
  true
);

COMMIT;

-- Verify — expect 50 rows from TOMO-0130 (Albert Tian) through TOMO-0179.
SELECT citizen_number, tomoland_id, name
FROM public.citizens
WHERE citizen_number BETWEEN 130 AND 179
ORDER BY citizen_number;
