-- Moves Aaron Weldy, F, and RYAN to the end of the directory (max + 1, +2, +3).
-- Leaves the 13–129 gap intact. Keeps citizen_number as GENERATED BY DEFAULT so
-- the app can assign max + 1 on new signups.
--
-- Run once in Supabase -> SQL Editor.

BEGIN;

ALTER TABLE public.citizens ALTER COLUMN citizen_number SET GENERATED BY DEFAULT;

UPDATE public.citizens
SET citizen_number = citizen_number + 2000
WHERE name IN ('Aaron Weldy', 'F', 'RYAN');

WITH max_num AS (
  SELECT COALESCE(MAX(citizen_number), 0) AS m
  FROM public.citizens
  WHERE name NOT IN ('Aaron Weldy', 'F', 'RYAN')
),
targets AS (
  SELECT
    c.id,
    ROW_NUMBER() OVER (
      ORDER BY
        CASE c.name
          WHEN 'Aaron Weldy' THEN 1
          WHEN 'F' THEN 2
          WHEN 'RYAN' THEN 3
        END
    ) - 1 AS idx
  FROM public.citizens c
  WHERE c.name IN ('Aaron Weldy', 'F', 'RYAN')
)
UPDATE public.citizens c
SET citizen_number = (SELECT m FROM max_num) + 1 + t.idx
FROM targets t
WHERE c.id = t.id;

SELECT setval(
  pg_get_serial_sequence('public.citizens', 'citizen_number'),
  (SELECT COALESCE(MAX(citizen_number), 1) FROM public.citizens),
  true
);

COMMIT;

-- Verify — last three rows should be Aaron, F, RYAN.
SELECT citizen_number, tomoland_id, name
FROM public.citizens
ORDER BY citizen_number DESC
LIMIT 5;
