-- Run once in Supabase -> SQL Editor
-- Renumbers citizen_number (and the derived tomoland_id) so Tomo is Resident #1,
-- followed by his inner circle in a specific order, then the rest of the
-- 'Tomo's Friend' batch alphabetically by name.
--
-- citizen_number is GENERATED ALWAYS AS IDENTITY, so it must be temporarily
-- switched to BY DEFAULT to allow explicit values, then switched back.
-- tomoland_id is a generated column derived from citizen_number, so it
-- updates automatically -- it is not touched directly.

BEGIN;

ALTER TABLE public.citizens ALTER COLUMN citizen_number SET GENERATED BY DEFAULT;

-- Phase 1: shift everyone out of the 1-62 target range to avoid transient
-- collisions with whatever unique constraint backs the identity column.
UPDATE public.citizens SET citizen_number = citizen_number + 1000;

-- Phase 2: assign final numbers per the requested order.
UPDATE public.citizens SET citizen_number = 1 WHERE id = 'ef479c74-dbaf-4b75-9100-1131abc5ddf1'; -- TOMO
UPDATE public.citizens SET citizen_number = 2 WHERE id = '4ec2be55-34af-4a8b-aa5b-1943ad6013a2'; -- justin quan
UPDATE public.citizens SET citizen_number = 3 WHERE id = 'f488c395-9d92-4059-b1d8-aac28fdd1df6'; -- RANDY PERECMAN
UPDATE public.citizens SET citizen_number = 4 WHERE id = '3d3173c0-d623-42c8-b4e2-cbada4fe226c'; -- RAYMOND CHEN
UPDATE public.citizens SET citizen_number = 5 WHERE id = 'a180edf7-8c4e-4199-8d94-659faab345b9'; -- VARUN NAIR
UPDATE public.citizens SET citizen_number = 6 WHERE id = '4eb4ad6a-45cd-4ad4-bb60-f9be49c77613'; -- JESSE LU
UPDATE public.citizens SET citizen_number = 7 WHERE id = '16e71c1c-ac50-427b-a066-05b30ce119f6'; -- TOMO TOMO TOMO SAHUR
UPDATE public.citizens SET citizen_number = 8 WHERE id = '591c0063-b8e9-45ce-899a-3324e1561d6e'; -- JACKY HUANG
UPDATE public.citizens SET citizen_number = 9 WHERE id = '909b92ec-f4f6-403a-b957-9fd13ca80e7f'; -- LUCAS QUAN
UPDATE public.citizens SET citizen_number = 10 WHERE id = 'dde05b25-f22e-48f3-bc3e-d2d10f1bb736'; -- RYLEE STANTON
UPDATE public.citizens SET citizen_number = 11 WHERE id = '6eb9d711-e9b8-4561-a4e0-44467872b723'; -- AMY GE
UPDATE public.citizens SET citizen_number = 12 WHERE id = 'a9aa76d8-c913-45e7-83aa-c1e36423b476'; -- KAREN LOU
UPDATE public.citizens SET citizen_number = 13 WHERE id = '87269eee-483b-490c-bf2c-3067c41f1efe'; -- Aaron Weldy
UPDATE public.citizens SET citizen_number = 14 WHERE id = '2b6efe62-5a49-47b0-ad5f-b1b7b337dc0c'; -- Albert Tian
UPDATE public.citizens SET citizen_number = 15 WHERE id = '554581e2-4190-421f-9fbb-8056bb3d2bc6'; -- Ally Nakamura
UPDATE public.citizens SET citizen_number = 16 WHERE id = 'd566408b-3613-45d2-8fd6-8e5335043199'; -- Amin Hamrah
UPDATE public.citizens SET citizen_number = 17 WHERE id = '97f19f57-63cf-410c-89f2-e0779ef4e66f'; -- Amy Zhou
UPDATE public.citizens SET citizen_number = 18 WHERE id = '5fee9f66-2e54-4987-a95d-742ba9da1284'; -- Andy
UPDATE public.citizens SET citizen_number = 19 WHERE id = '5e3058a8-7a4d-4ea0-9501-2f371ea7ff45'; -- Annie Ma
UPDATE public.citizens SET citizen_number = 20 WHERE id = '037bfd28-15c3-4716-9a92-6edf4deb2eb3'; -- Arman Kumaraswamy
UPDATE public.citizens SET citizen_number = 21 WHERE id = '5fcb9059-1a49-492d-ad3b-b46757f7784a'; -- Bassil Shama
UPDATE public.citizens SET citizen_number = 22 WHERE id = '82d7c04f-e435-48bd-bc27-2dfa0b6781f8'; -- Bill
UPDATE public.citizens SET citizen_number = 23 WHERE id = 'a33d6d88-d89f-40d5-9780-1d0f64eb42fd'; -- Charles Gao
UPDATE public.citizens SET citizen_number = 24 WHERE id = 'd64f26b3-d810-46ce-99b1-be899a1f490d'; -- Chrissy Sun
UPDATE public.citizens SET citizen_number = 25 WHERE id = '965ea3f4-7ba7-4258-bee4-0c4ac6f331e2'; -- Christina Melas-Kyriazi
UPDATE public.citizens SET citizen_number = 26 WHERE id = '698e2cd1-0f3b-4a2d-a589-b0964af5ad73'; -- Christopher Zhu
UPDATE public.citizens SET citizen_number = 27 WHERE id = 'd59f9f59-d1aa-4078-8dd3-36655f35c374'; -- Emma
UPDATE public.citizens SET citizen_number = 28 WHERE id = 'd6270506-b67f-4769-8734-9f3e63530316'; -- Eunice Lai
UPDATE public.citizens SET citizen_number = 29 WHERE id = '369a8dfa-a78b-4104-be83-1b3cfbc20837'; -- Foy
UPDATE public.citizens SET citizen_number = 30 WHERE id = 'a6211bc1-2d3e-400d-b055-002d33fcb4e9'; -- Haris
UPDATE public.citizens SET citizen_number = 31 WHERE id = '76fa431f-cde1-49a9-a643-f388cd31bc6d'; -- Hyden Polikoff
UPDATE public.citizens SET citizen_number = 32 WHERE id = '9b9b3567-d43c-42d8-8619-613decf5bd85'; -- Jackie Chen
UPDATE public.citizens SET citizen_number = 33 WHERE id = '43e56a4d-d2ca-47dd-bd81-dbb6375c37f0'; -- Jae Park
UPDATE public.citizens SET citizen_number = 34 WHERE id = 'ea75fe69-1724-4f4b-8ee0-c8d13116c7ef'; -- Jenny Sun
UPDATE public.citizens SET citizen_number = 35 WHERE id = '5c08fef6-0122-4247-bd04-84fc948620e4'; -- Jia Chen
UPDATE public.citizens SET citizen_number = 36 WHERE id = 'd557101d-4cab-4395-a9c6-57f98aed5a4c'; -- Justin Quan
UPDATE public.citizens SET citizen_number = 37 WHERE id = '588ef8a1-4c94-4993-8b77-62c224a6f0be'; -- Kaitlyn Luo
UPDATE public.citizens SET citizen_number = 38 WHERE id = '642f151d-daf3-44e4-bc6e-f57bb3e525e1'; -- Ker Lee Yap
UPDATE public.citizens SET citizen_number = 39 WHERE id = 'a6759808-bcc5-49ab-84bb-818ae73bd743'; -- Maja Wilbrink
UPDATE public.citizens SET citizen_number = 40 WHERE id = 'b672ef48-4e79-4d4d-a4d1-207f1e18ef30'; -- Mathurah Ravigulan
UPDATE public.citizens SET citizen_number = 41 WHERE id = '4bd64b6c-1c1d-48c5-8e23-6c084adede60'; -- Matthew Guillod
UPDATE public.citizens SET citizen_number = 42 WHERE id = '48d1c483-af80-4fd1-9294-a41a9e9e8818'; -- Megan Mou
UPDATE public.citizens SET citizen_number = 43 WHERE id = '983bebd0-e3a7-4e8a-a181-467dfff55a30'; -- Mei Mei
UPDATE public.citizens SET citizen_number = 44 WHERE id = 'ffebc008-af64-4f9d-b649-3cb142ebd9f3'; -- Michael Zhu
UPDATE public.citizens SET citizen_number = 45 WHERE id = 'dc22c592-a4ad-4c16-99cc-2cb14e5eea82'; -- Michelle Schwartzman
UPDATE public.citizens SET citizen_number = 46 WHERE id = '0cbf8c44-e0ea-4380-a8fe-57213ec98f50'; -- Ming
UPDATE public.citizens SET citizen_number = 47 WHERE id = '1f5cd7fc-1dac-4f8f-bae2-12e178eeb4ab'; -- Nalin Semwal
UPDATE public.citizens SET citizen_number = 48 WHERE id = '09c7d02e-3588-41b3-b488-e97bbdcd6377'; -- Nick O'Brien
UPDATE public.citizens SET citizen_number = 49 WHERE id = '2bfa3a02-ed3a-4e0b-9189-574ea023c47f'; -- Nicole Summer Hsing
UPDATE public.citizens SET citizen_number = 50 WHERE id = 'f2e16407-32dc-4bcb-a68c-c33ac92a8875'; -- Raymond Ma Quan
UPDATE public.citizens SET citizen_number = 51 WHERE id = '235dcb04-82f2-47fb-bd6e-7890f587e154'; -- Rohil Agarwal
UPDATE public.citizens SET citizen_number = 52 WHERE id = '432b268c-5903-4b6f-aaba-81fd197ddfc9'; -- Ryan Kim
UPDATE public.citizens SET citizen_number = 53 WHERE id = 'fc4802ab-93d1-4a44-845c-0c975ee6e5c5'; -- Shaahana Naufal
UPDATE public.citizens SET citizen_number = 54 WHERE id = 'dfa18566-6e4e-4b0e-975d-717bafb2be11'; -- Si Jia Wen
UPDATE public.citizens SET citizen_number = 55 WHERE id = '5392ecc3-9b23-471b-a63f-3b7264cfd7ea'; -- Simon
UPDATE public.citizens SET citizen_number = 56 WHERE id = '88ea7177-8b58-4720-bb5e-3910aeac2ab4'; -- Simon Wijckman
UPDATE public.citizens SET citizen_number = 57 WHERE id = 'fc6954be-a65b-4d8d-8198-fe68db5912a3'; -- Ted Chai
UPDATE public.citizens SET citizen_number = 58 WHERE id = '98168662-17fb-48e5-bb45-7525c90a4e98'; -- Tiffany
UPDATE public.citizens SET citizen_number = 59 WHERE id = 'adf077f8-c683-466a-a65d-67366bb00e86'; -- Tyler McNierney
UPDATE public.citizens SET citizen_number = 60 WHERE id = 'd47e3562-2996-4b8a-9590-f1e2bca0897f'; -- Will Hoppin
UPDATE public.citizens SET citizen_number = 61 WHERE id = '2b695967-b903-4e2b-b1cb-d3a59d6b4030'; -- Yang Fan Yun
UPDATE public.citizens SET citizen_number = 62 WHERE id = '42232f29-c69a-41e2-8cf7-20f84199fa22'; -- Zen

-- Resume the sequence after the highest manually-assigned number.
SELECT setval(pg_get_serial_sequence('public.citizens', 'citizen_number'), 63, false);

ALTER TABLE public.citizens ALTER COLUMN citizen_number SET GENERATED ALWAYS;

COMMIT;
