-- Keeps citizen_number as GENERATED BY DEFAULT and syncs the identity sequence to
-- max(citizen_number). Required for the app to assign max + 1 on new signups
-- (gaps like 13–129 are intentional and never filled).
--
-- Run after any renumber script that restores GENERATED ALWAYS.

ALTER TABLE public.citizens ALTER COLUMN citizen_number SET GENERATED BY DEFAULT;

SELECT setval(
  pg_get_serial_sequence('public.citizens', 'citizen_number'),
  (SELECT COALESCE(MAX(citizen_number), 1) FROM public.citizens),
  true
);
